version: '2'

services:
  db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: db
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=p@ssw0rd1
      ports:
        - 1433:1433